#!/usr/bin/env python3
"""Download lpac + its shared-library closure from Alpine, pinned by sha256.

  alpine_closure.py            download exactly what alpine.lock lists, verify sha256
  alpine_closure.py --relock   resolve the closure again from ALPINE_BRANCH's
                               APKINDEX and rewrite alpine.lock (then rebuild + test
                               on a device before committing the new lock)

Pinned to a stable Alpine branch (not edge): edge replaces packages daily and old
.apk files vanish from the mirror. A stable branch only changes on security fixes;
if a pinned file is gone, the download fails loudly and you run --relock.
Output: scripts/esim/alpine-pkgs/<name>-<ver>.apk (git-ignored cache).
"""
import hashlib, io, os, sys, tarfile, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
LOCK = os.path.join(HERE, "alpine.lock")
OUT = os.environ.get("ALPINE_PKGS_DIR", os.path.join(HERE, "alpine-pkgs"))
MIRROR = os.environ.get("ALPINE_MIRROR", "https://dl-cdn.alpinelinux.org/alpine")
ARCH = "aarch64"

def fetch(url):
    with urllib.request.urlopen(url, timeout=120) as r:
        return r.read()

def sha256(b):
    return hashlib.sha256(b).hexdigest()

def relock(branch, start="lpac"):
    pkgs, provides = {}, {}
    for repo in ("community", "main"):
        raw = fetch(f"{MIRROR}/{branch}/{repo}/{ARCH}/APKINDEX.tar.gz")
        with tarfile.open(fileobj=io.BytesIO(raw), mode="r:gz") as tf:
            idx = tf.extractfile("APKINDEX").read().decode()
        for block in idx.split("\n\n"):
            f = {}
            for line in block.splitlines():
                if len(line) > 2 and line[1] == ":":
                    f.setdefault(line[0], line[2:])
            if "P" not in f:
                continue
            name = f["P"]
            deps = [d for d in f.get("D", "").split() if d.startswith("so:")]
            pkgs.setdefault(name, (repo, f["V"], deps))
            for p in f.get("p", "").split():
                p = p.split("=")[0]
                if p.startswith("so:"):
                    provides.setdefault(p, name)
    resolved, queue, rows = set(), [start], []
    while queue:
        name = queue.pop()
        if name in resolved or name not in pkgs:
            continue
        resolved.add(name)
        repo, ver, deps = pkgs[name]
        data = fetch(f"{MIRROR}/{branch}/{repo}/{ARCH}/{name}-{ver}.apk")
        rows.append(f"{branch}/{repo} {name} {ver} {sha256(data)}")
        for d in deps:
            if "musl" in d:          # the device's own libc
                continue
            prov = provides.get(d)
            if prov:
                queue.append(prov)
            else:
                print(f"WARN: no provider for {d} (needed by {name})", file=sys.stderr)
    with open(LOCK, "w") as fh:
        fh.write(f"# lpac closure for aarch64, generated by alpine_closure.py --relock ({branch})\n")
        fh.write("# branch/repo  package  version  sha256(.apk)\n")
        fh.write("\n".join(sorted(rows, key=lambda r: r.split()[1])) + "\n")
    print(f"wrote {LOCK} ({len(rows)} packages)")

def download():
    os.makedirs(OUT, exist_ok=True)
    for line in open(LOCK):
        if not line.strip() or line.startswith("#"):
            continue
        path, name, ver, want = line.split()
        fn = f"{name}-{ver}.apk"
        dest = os.path.join(OUT, fn)
        data = open(dest, "rb").read() if os.path.exists(dest) else None
        if data is None or sha256(data) != want:
            print(f"fetch {path}/{fn}")
            try:
                data = fetch(f"{MIRROR}/{path}/{ARCH}/{fn}")
            except Exception as e:
                sys.exit(f"ERROR: {fn} not downloadable ({e}); Alpine replaced it — "
                         f"run alpine_closure.py --relock and re-test on a device")
            if sha256(data) != want:
                sys.exit(f"ERROR: sha256 mismatch for {fn}")
            open(dest, "wb").write(data)
    print("OK: all packages match alpine.lock")

if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--relock":
        relock(os.environ.get("ALPINE_BRANCH", "v3.24"))
    else:
        download()
